// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: bookApi.proto

package trpc_cros_bookApi

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId int32 `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *BookId) Reset() {
	*x = BookId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookApi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookId) ProtoMessage() {}

func (x *BookId) ProtoReflect() protoreflect.Message {
	mi := &file_bookApi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookId.ProtoReflect.Descriptor instead.
func (*BookId) Descriptor() ([]byte, []int) {
	return file_bookApi_proto_rawDescGZIP(), []int{0}
}

func (x *BookId) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId int32   `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author string  `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Price  int32   `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Score  float32 `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookApi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_bookApi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_bookApi_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type BookParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BookParams) Reset() {
	*x = BookParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookApi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookParams) ProtoMessage() {}

func (x *BookParams) ProtoReflect() protoreflect.Message {
	mi := &file_bookApi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookParams.ProtoReflect.Descriptor instead.
func (*BookParams) Descriptor() ([]byte, []int) {
	return file_bookApi_proto_rawDescGZIP(), []int{2}
}

func (x *BookParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_bookApi_proto protoreflect.FileDescriptor

var file_bookApi_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x41,
	0x70, 0x69, 0x22, 0x20, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x6f,
	0x6f, 0x6b, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x6f,
	0x6f, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x20, 0x0a, 0x0a,
	0x42, 0x6f, 0x6f, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x94,
	0x01, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x70, 0x69, 0x12, 0x47, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x74, 0x72, 0x70, 0x63,
	0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x70, 0x69, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x17, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e,
	0x63, 0x72, 0x6f, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x17, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x41, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x19, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e,
	0x63, 0x72, 0x6f, 0x73, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x49, 0x64, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bookApi_proto_rawDescOnce sync.Once
	file_bookApi_proto_rawDescData = file_bookApi_proto_rawDesc
)

func file_bookApi_proto_rawDescGZIP() []byte {
	file_bookApi_proto_rawDescOnce.Do(func() {
		file_bookApi_proto_rawDescData = protoimpl.X.CompressGZIP(file_bookApi_proto_rawDescData)
	})
	return file_bookApi_proto_rawDescData
}

var file_bookApi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bookApi_proto_goTypes = []any{
	(*BookId)(nil),     // 0: trpc.cros.bookApi.BookId
	(*Book)(nil),       // 1: trpc.cros.bookApi.Book
	(*BookParams)(nil), // 2: trpc.cros.bookApi.BookParams
}
var file_bookApi_proto_depIdxs = []int32{
	2, // 0: trpc.cros.bookApi.BookApi.GetBookInfo:input_type -> trpc.cros.bookApi.BookParams
	1, // 1: trpc.cros.bookApi.BookApi.SaveBook:input_type -> trpc.cros.bookApi.Book
	1, // 2: trpc.cros.bookApi.BookApi.GetBookInfo:output_type -> trpc.cros.bookApi.Book
	0, // 3: trpc.cros.bookApi.BookApi.SaveBook:output_type -> trpc.cros.bookApi.BookId
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bookApi_proto_init() }
func file_bookApi_proto_init() {
	if File_bookApi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bookApi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BookId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookApi_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookApi_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BookParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bookApi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookApi_proto_goTypes,
		DependencyIndexes: file_bookApi_proto_depIdxs,
		MessageInfos:      file_bookApi_proto_msgTypes,
	}.Build()
	File_bookApi_proto = out.File
	file_bookApi_proto_rawDesc = nil
	file_bookApi_proto_goTypes = nil
	file_bookApi_proto_depIdxs = nil
}
